batch_size: 16
epochs: 32
num_votes: 3

train_dataset:
  type: S3DIS
  dataset_root: 'data/stanford_indoor3d'
  mode: train
  val_area: 5
  transforms:
    - type: RandomFeatContrast
      prob: 0.2
      blend_factor: None
    - type: RandomRotatePositionByZ
    - type: RandomFeatDrop
      drop_ratio: 0.2
    - type: FeatNormalize
      color_mean: [ 0.5, 0.5, 0.5 ]
      color_std: [ 0.5, 0.5, 0.5 ]

val_dataset:
  type: ScannetDatasetWholeScene
  dataset_root: 'data/stanford_indoor3d'
  mode: val
  val_area: 5
  stride: 0.5
  block_size: 1.0
  transforms:
    - type: FeatNormalize
      color_mean: [ 0.5, 0.5, 0.5 ]
      color_std: [ 0.5, 0.5, 0.5 ]

model:
  type: PointNetV2
  in_channels: 9
  num_classes: 13
  use_msg: False
  n_samples: 32

optimizer:
#  _inherited_: False
  type: Adam
  weight_decay: 0.0001

loss:
  types:
    - type: CrossEntropyLoss
      label_smoothing: 0.2
  coef: [1]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0.0
  power: 0.9
