_base_: '../_base_/s3dis.yml'

batch_size: 4
epochs: 200

model:
  type: PointNet
  in_channels: 7
  num_classes: 13

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 0.00001

loss:
  types:
    - type: CrossEntropyLoss
      label_smoothing: 0.2
  coef: [1]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.005
  end_lr: 0.0
  power: 0.9
