_base_: '../_base_/s3dis.yml'

batch_size: 4
epochs: 200

model:
  type: PointNet
  in_channels: 6
  num_classes: 13

optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
